pretrained: false
checkpoint: ???
mode: test

model:
  model_name: ZF
  zf_method: SENSE
  fft_type: fft_norm_only
  num_log_images: 16

  test_ds:
    data_path: ???
    dataset_type: FastMRI
    challenge: multicoil
    fft_type: fft_norm_only
    mask_args:
      type: None
      shift_mask: true
      use_seed: false
    normalize_inputs: false
    crop_size: None
    crop_before_masking: true
    kspace_zero_filling_size: None
    sample_rate: 1
    batch_size: 1
    shuffle: false
    num_workers: 8
    drop_last: false
    pin_memory: false

trainer:
  strategy: ddp
  gpus: 1
  num_nodes: 1
  max_epochs: 200
  precision: 16
  enable_checkpointing: false
  logger: false
  log_every_n_steps: 50
  check_val_every_n_epoch: -1
  max_steps: -1

exp_manager:
  name: ???
  create_tensorboard_logger: true
  create_wandb_logger: false
  files_to_copy: []
