pretrained: false
checkpoint: ???
mode: test

model:
  model_name: ZF
  device: cuda
  use_sens_net: false
  dimensionality: 2
  consecutive_slices: 1
  coil_combination_method: SENSE
  fft_centered: true
  fft_normalization: ortho
  spatial_dims:
    - -2
    - -1
  coil_dim: 1
  complex_data: true
  log_images: true

  test_ds:
    data_path: /scratch/iskylitsis/data/mridata_knee_2019/test
    coil_sensitivity_maps_path: None
    mask_path: None
    sample_rate: 1
    volume_sample_rate: None
    use_dataset_cache: false
    dataset_cache_file: None
    num_cols: None
    consecutive_slices: 1
    data_saved_per_slice: false
    apply_prewhitening: false
    apply_gcc: false
    coil_combination_method: SENSE
    dimensionality: 2
    mask_args:
      type: poisson2d
      accelerations:
      - 12
      center_fractions:
      - 0.7
      scale: 0.02
      shift_mask: false
      use_seed: false
    half_scan_percentage: 0.0
    remask: false
    ssdu: false
    n2r: false
    crop_size: None
    kspace_crop: false
    crop_before_masking: true
    kspace_zero_filling_size: None
    normalize_inputs: true
    normalization_type: max
    kspace_normalization: false
    fft_centered: true
    fft_normalization: ortho
    spatial_dims:
    - -2
    - -1
    coil_dim: 1
    use_seed: false
    batch_size: 1
    shuffle: false
    num_workers: 4
    pin_memory: false
    drop_last: false

  optim:
    name: adam
    lr: 1e-4
    betas:
    - 0.9
    - 0.999
    weight_decay: 0.0001
    sched:
      name: InverseSquareRootAnnealing
      min_lr: 0.0
      last_epoch: -1
      warmup_ratio: 0.1

trainer:
  strategy: ddp_find_unused_parameters_false
  accelerator: gpu
  devices: 1
  num_nodes: 1
  max_epochs: 2000
  precision: 16
  enable_checkpointing: false
  logger: false
  log_every_n_steps: 50
  check_val_every_n_epoch: -1
  max_steps: -1

exp_manager:
  exp_dir: /data/projects/recon/other/dkarkalousos/UnSelfSupervised/reconstructions_stanford_knees_poisson2d_12x/ZF
  create_tensorboard_logger: true
  create_wandb_logger: false
  wandb_logger_kwargs:
    project: ???
  files_to_copy: [ ]
