pretrained: false
checkpoint: ???
mode: test

model:
  model_name: ZF
  device: cuda
  use_sens_net: false
  dimensionality: 2
  consecutive_slices: 1
  coil_combination_method: RSS
  fft_centered: true
  fft_normalization: ortho
  spatial_dims:
    - -2
    - -1
  coil_dim: 1
  complex_data: true
  log_images: true

  test_ds:
    data_path: /data/projects/recon/data/public/fastmri/brain/data/FLAIR/multicoil_val
    coil_sensitivity_maps_path: None
    mask_path: None
    sample_rate: 1
    volume_sample_rate: None
    use_dataset_cache: false
    dataset_cache_file: None
    num_cols: None
    consecutive_slices: 1
    data_saved_per_slice: false
    apply_prewhitening: false
    apply_gcc: false
    gcc_virtual_coils: 8
    gcc_calib_lines: 24
    gcc_align_data: true
    coil_combination_method: RSS
    dimensionality: 2
    mask_args:
      type: none
      use_seed: false
    half_scan_percentage: 0.0
    remask: false
    ssdu: false
    crop_size: [320, 320]
    kspace_crop: false
    crop_before_masking: true
    kspace_zero_filling_size: None
    normalize_inputs: true
    normalization_type: max
    kspace_normalization: false
    fft_centered: true
    fft_normalization: ortho
    spatial_dims:
      - -2
      - -1
    coil_dim: 1
    use_seed: false
    batch_size: 1
    shuffle: false
    num_workers: 8
    pin_memory: false
    drop_last: false

trainer:
  strategy: ddp_find_unused_parameters_false
  accelerator: gpu
  devices: 1
  num_nodes: 1
  max_epochs: 200
  precision: 16
  enable_checkpointing: false
  logger: false
  log_every_n_steps: 50
  check_val_every_n_epoch: -1
  max_steps: -1

exp_manager:
  exp_dir: /data/projects/recon/other/dkarkalousos/UnSelfSupervised/reconstructions/targets_RSS_fastmri_brain_FLAIR/
  create_tensorboard_logger: true
  create_wandb_logger: false
  wandb_logger_kwargs:
    project: ???
  files_to_copy: [ ]
