pretrained: false
checkpoint: ???
mode: test

model:
  model_name: CS
  cs_type: l1_wavelet
  reg_wt: 1.2
  num_iters: 60
  center_kspace: false
  center_sensitivity_maps: true
  center_mask: false
  center_reconstruction: true
  use_sens_net: false
  dimensionality: 2
  consecutive_slices: 1
  coil_combination_method: SENSE
  fft_centered: false
  fft_normalization: backward
  spatial_dims:
    - -2
    - -1
  coil_dim: 1
  complex_data: true
  log_images: true

  test_ds:
    data_path: /data/projects/recon/data/public/3D_FSE_PD_Knees/test.json
    sense_path: None
    mask_path: None
    initial_predictions_path: None
    challenge: multicoil
    batch_size: 1
    sample_rate: 1
    volume_sample_rate: None
    use_dataset_cache: false
    dataset_cache_file: None
    num_cols: None
    consecutive_slices: 1
    data_saved_per_slice: false
    complex_data: true
    apply_prewhitening: false
    apply_gcc: false
    coil_combination_method: SENSE
    dimensionality: 2
    mask_args:
      type: poisson2d
      accelerations:
        - 12
      center_fractions:
        - 0.7
      scale: 0.02
      shift_mask: true
      use_seed: false
    half_scan_percentage: 0.0
    remask: false
    crop_size: None
    kspace_crop: false
    crop_before_masking: true
    kspace_zero_filling_size: None
    normalize_inputs: false
    normalization_type: max
    kspace_normalization: false
    fft_centered: false
    fft_normalization: backward
    spatial_dims:
      - -2
      - -1
    coil_dim: 1
    use_seed: false
    shuffle: false
    num_workers: 8
    drop_last: false
    pin_memory: false

trainer:
  strategy: ddp
  accelerator: gpu
  devices: 1
  num_nodes: 1
  max_epochs: 200
  precision: 16
  enable_checkpointing: false
  logger: false
  log_every_n_steps: 50
  check_val_every_n_epoch: -1
  max_steps: -1

exp_manager:
  exp_dir: /data/projects/recon/other/dkarkalousos/UnSelfSupervised/reconstructions/CS/
  create_tensorboard_logger: true
  create_wandb_logger: false
  wandb_logger_kwargs:
    project: ???
  files_to_copy: [ ]
