pretrained: true
checkpoint: /data/projects/recon/other/dkarkalousos/trained_models/fastMRI_FLAIR_equispaced1d_4x_320x320/CIRIM_5C_64F_ssim_NODC/--val_loss=0.2787-epoch=19.ckpt
mode: test

model:
  model_name: CIRIM
  recurrent_layer: IndRNN
  conv_filters:
    - 64
    - 64
    - 2
  conv_kernels:
    - 5
    - 3
    - 3
  conv_dilations:
    - 1
    - 2
    - 1
  conv_bias:
    - true
    - true
    - false
  recurrent_filters:
    - 64
    - 64
    - 0
  recurrent_kernels:
    - 1
    - 1
    - 0
  recurrent_dilations:
    - 1
    - 1
    - 0
  recurrent_bias:
    - true
    - true
    - false
  depth: 2
  time_steps: 8
  conv_dim: 2
  num_cascades: 5
  no_dc: true
  keep_eta: true
  output_type: SENSE
  use_sens_net: false
  sens_chans: 8
  sens_pools: 4
  sens_mask_type: 1D
  sens_normalize: true
  mask_center: true
  train_loss_fn: ssim
  eval_loss_fn: ssim
  accumulate_estimates: true
  fft_type: orthogonal

  test_ds:
    data_path: /data/projects/recon/data/public/fastmri/brain/data/FLAIR/multicoil_val
    sense_data_path: /data/projects/recon/data/public/fastmri/brain/sensitivities_maps/FLAIR
    dataset_type: FastMRI
    challenge: multicoil
    fft_type: orthogonal
    mask_args:
      type: equispaced1d
      accelerations:
      - 4
      center_fractions:
      - 0.08
      scale: 0.02
      shift_mask: false
      use_seed: false
    normalize_inputs: true
    crop_size: [320, 320]
    crop_before_masking: true
    kspace_zero_filling_size: None
    sample_rate: 1
    batch_size: 1
    shuffle: false
    num_workers: 8
    drop_last: false
    pin_memory: false

  optim:
    name: adam
    lr: 0.001
    betas:
      - 0.9
      - 0.98
    weight_decay: 0.0
    sched:
      name: InverseSquareRootAnnealing
      min_lr: 0.0
      last_epoch: -1
      warmup_ratio: 0.1

trainer:
  strategy: ddp
  gpus: 1
  num_nodes: 1
  max_epochs: 20
  precision: 16
  enable_checkpointing: false
  logger: false
  log_every_n_steps: 50
  check_val_every_n_epoch: -1
  max_steps: -1

exp_manager:
  name: /data/projects/recon/other/dkarkalousos/UnSelfSupervised/reconstructions/CIRIM_5C_64F_ssim_NODC_fastmri_brain_FLAIR_Equispaced1d_4x
  create_tensorboard_logger: true
  files_to_copy: [ ]
