# Coverage configuration
# ----------------------
coverage:
  status:
    patch: true

  range: 60..100     # First number represents red, and second represents green
  # (default is 70..100)
  round: nearest       # up, down, or nearest
  precision: 2      # Number of decimal places, between 0 and 5

# Ignoring Paths
# --------------
# which folders/files to ignore
ignore:
#  - mridc/collections/common/data/*
#  - mridc/collections/common/metrics/*
#  - mridc/collections/common/parts/patch_utils.py
#  - mridc/collections/common/parts/ptl_overrides.py
#  - mridc/collections/segmentation/metrics/distance.py
#  - mridc/collections/reconstruction/models/pics.py
#  - mridc/collections/reconstruction/models/zf.py
#  - mridc/core/classes/module.py
#  - mridc/core/optim/adafactor.py
#  - mridc/core/optim/novograd.py
#  - mridc/core/optim/radam.py
#  - mridc/core/utils/numba_utils.py
#  - mridc/utils/decorators/*
#  - mridc/utils/cloud.py
#  - mridc/utils/arguments.py
#  - mridc/utils/debug_hook.py
#  - mridc/launch.py
  - projects/*
  - projects/quantitative/datasets/ahead/*
  - setup.py

# Pull request comments:
# ----------------------
# Diff is the Coverage Diff of the pull request.
# Files are the files impacted by the pull request
comment:
  layout: diff, files  # accepted in any order: reach, diff, flags, and/or files
