[tool.black]
line-length = 119
target-version = ['py38', 'py39']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.idea
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py38, py39
skip_missing_interpreters=true
[gh-actions]
python =
    3.8: py38
    3.9: py39
[testenv]
deps = pytest
extras = dev
allowlist_externals = sh
commands=
     sh -c "pytest --ignore=projects"
"""

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 119
