[tool.black]
line-length = 119
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.idea
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py310
skip_missing_interpreters=true
[gh-actions]
python =
    3.10: py310
[testenv]
deps = pytest
extras = dev
allowlist_externals = sh
commands=
     sh -c "pytest --ignore=projects"
"""
