pretrained: false
checkpoint: None
mode: train

model:
  model_name: SEGMENTATIONUNETR
  use_reconstruction_module: false
  segmentation_module: UNETR
  segmentation_module_input_channels: 1
  segmentation_module_output_channels: 2
  segmentation_module_img_size:  # needs to be defined
    - 180
    - 200
  segmentation_module_channels: 64
  segmentation_module_hidden_size: 768
  segmentation_module_mlp_dim: 3072
  segmentation_module_num_heads: 12
  segmentation_module_pos_embed: conv
  segmentation_module_norm_name: instance
  segmentation_module_conv_block: true
  segmentation_module_res_block: true
  segmentation_module_dropout: 0.0
  segmentation_module_qkv_bias: false
  dimensionality: 2
  segmentation_loss_fn:
    - cross_entropy
    - dice
  cross_entropy_loss_weighting_factor: 0.5
  cross_entropy_loss_num_samples: 1
  cross_entropy_loss_ignore_index: -100
  cross_entropy_loss_reduction: mean
  cross_entropy_loss_label_smoothing: 0.0
  cross_entropy_loss_weight: [ 0.5, 0.5 ]
  dice_loss_weighting_factor: 0.5
  dice_loss_include_background: true # always set to true if the background is removed
  dice_loss_to_onehot_y: false
  dice_loss_sigmoid: false
  dice_loss_softmax: false
  dice_loss_other_act: none
  dice_loss_squared_pred: false
  dice_loss_jaccard: false
  dice_loss_flatten: false
  dice_loss_reduction: mean_batch
  dice_loss_smooth_nr: 1e-5
  dice_loss_smooth_dr: 1e-5
  dice_loss_batch: true
  cross_entropy_metric_num_samples: 1
  cross_entropy_metric_ignore_index: -100
  cross_entropy_metric_reduction: mean
  cross_entropy_metric_label_smoothing: 0.0
  cross_entropy_metric_weight: [ 0.5, 0.5 ]
  dice_metric_include_background: true # always set to true if the background is removed
  dice_metric_to_onehot_y: false
  dice_metric_sigmoid: false
  dice_metric_softmax: false
  dice_metric_other_act: none
  dice_metric_squared_pred: false
  dice_metric_jaccard: false
  dice_metric_flatten: false
  dice_metric_reduction: mean_batch
  dice_metric_smooth_nr: 1e-5
  dice_metric_smooth_dr: 1e-5
  dice_metric_batch: true
  segmentation_classes_thresholds:
    - 0.5  # Brain Tissue
    - 0.5  # Pathology
  fft_centered: false
  fft_normalization: backward
  spatial_dims:
    - -2
    - -1
  coil_dim: 1
  coil_combination_method: SENSE
  use_sens_net: false
  consecutive_slices: 1
  magnitude_input: true
  normalize_segmentation_output: true
  complex_data: true
  log_images: true

  train_ds:
    data_path: ???
    coil_sensitivity_maps_path: None
    mask_path: None
    sample_rate: 1
    volume_sample_rate: None
    use_dataset_cache: false
    dataset_cache_file: None
    num_cols: None
    consecutive_slices: 1
    data_saved_per_slice: false
    apply_prewhitening: false
    apply_gcc: false
    coil_combination_method: SENSE
    dimensionality: 2
    mask_args:
      type: poisson2d
      accelerations:
        - 8
      center_fractions:
        - 0.7
      scale: 0.02
      shift_mask: true
      use_seed: true
    half_scan_percentage: 0.0
    remask: false
    crop_size: None
    kspace_crop: false
    crop_before_masking: true
    kspace_zero_filling_size: None
    normalize_inputs: true
    normalization_type: max
    kspace_normalization: false
    fft_centered: false
    fft_normalization: backward
    spatial_dims:
      - -2
      - -1
    coil_dim: 1
    use_seed: true
    segmentations_path: None
    initial_predictions_path: None
    segmentation_classes: 2
    segmentation_classes_to_remove:
      - 0  # Background
    segmentation_classes_to_combine:
      - 1  # GM
      - 2  # WM
    segmentation_classes_to_separate:
      - 3  # Pathology
    segmentation_classes_thresholds:
      - 0.5  # GM + WM
      - 0.5  # Pathology
    complex_data: true
    batch_size: 1
    shuffle: true
    num_workers: 8
    pin_memory: false
    drop_last: false

  validation_ds:
    data_path: ???
    coil_sensitivity_maps_path: None
    mask_path: None
    sample_rate: 1
    volume_sample_rate: None
    use_dataset_cache: false
    dataset_cache_file: None
    num_cols: None
    consecutive_slices: 1
    data_saved_per_slice: false
    apply_prewhitening: false
    apply_gcc: false
    coil_combination_method: SENSE
    dimensionality: 2
    mask_args:
      type: poisson2d
      accelerations:
        - 8
      center_fractions:
        - 0.7
      scale: 0.02
      shift_mask: true
      use_seed: false
    half_scan_percentage: 0.0
    remask: false
    crop_size: None
    kspace_crop: false
    crop_before_masking: true
    kspace_zero_filling_size: None
    normalize_inputs: true
    normalization_type: max
    kspace_normalization: false
    fft_centered: false
    fft_normalization: backward
    spatial_dims:
      - -2
      - -1
    coil_dim: 1
    use_seed: false
    segmentations_path: None
    initial_predictions_path: None
    segmentation_classes: 2
    segmentation_classes_to_remove:
      - 0  # Background
    segmentation_classes_to_combine:
      - 1  # GM
      - 2  # WM
    segmentation_classes_to_separate:
      - 3  # Pathology
    segmentation_classes_thresholds:
      - 0.5  # GM + WM
      - 0.5  # Pathology
    complex_data: true
    batch_size: 1
    shuffle: false
    num_workers: 8
    pin_memory: false
    drop_last: false

  optim:
    name: adam
    lr: 1e-4
    betas:
      - 0.9
      - 0.98
    weight_decay: 0.0
    sched:
      name: InverseSquareRootAnnealing
      min_lr: 0.0
      last_epoch: -1
      warmup_ratio: 0.1

trainer:
  strategy: ddp
  accelerator: gpu
  devices: 1
  num_nodes: 1
  max_epochs: 50
  precision: 32
  enable_checkpointing: false
  logger: false
  log_every_n_steps: 50
  check_val_every_n_epoch: -1
  max_steps: -1

exp_manager:
  exp_dir: ???
  create_tensorboard_logger: true
  create_wandb_logger: false
  wandb_logger_kwargs:
    project: ???
  files_to_copy: [ ]
