version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test-python38:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          app-dir: ~/project/requirements/
      - run:
          name: Run tests python 3.8
          command: pytest
  build-and-test-python39:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          app-dir: ~/project/requirements/
      - run:
          name: Run tests python 3.9
          command: pytest

workflows:
  sample:
    jobs:
      - build-and-test-python38
      - build-and-test-python39
