pretrained: true
checkpoint: ???
mode: test

model:
  model_name: SEGMENTATIONUNET
  use_reconstruction_module: false
  segmentation_module: UNet
  segmentation_module_input_channels: 2
  segmentation_module_output_channels: 4
  segmentation_module_channels: 32
  segmentation_module_pooling_layers: 4
  segmentation_module_dropout: 0.1
  segmentation_loss_fn:
    - cross_entropy
    - dice
  cross_entropy_loss_num_samples: 1
  cross_entropy_loss_ignore_index: -100
  cross_entropy_loss_reduction: none
  cross_entropy_loss_label_smoothing: 0.0
  cross_entropy_loss_weight: none
  cross_entropy_loss_normalization: softmax
  coil_combination_method: SENSE
  dice_loss_batched: false
  dice_loss_include_background: true
  dice_loss_squared_pred: false
  dice_loss_normalization: softmax
  dice_loss_epsilon: 1
  cross_entropy_metric_num_samples: 1
  cross_entropy_metric_ignore_index: -100
  cross_entropy_metric_reduction: none
  cross_entropy_metric_label_smoothing: 0.0
  cross_entropy_metric_weight: none
  cross_entropy_metric_normalization: softmax
  dice_coefficient_batched: false
  dice_coefficient_include_background: true
  dice_coefficient_squared_pred: false
  dice_coefficient_normalization: softmax
  dice_coefficient_epsilon: 1
  consecutive_slices: 3
  use_sens_net: false
  sens_chans: 8
  sens_pools: 4
  sens_mask_type: 2D
  fft_centered: false
  fft_normalization: backward
  spatial_dims:
    - -2
    - -1
  coil_dim: 2

  test_ds:
    data_path: ???
    sense_path: None
    mask_path: None
    batch_size: 1
    sample_rate: 1
    volume_sample_rate: None
    use_dataset_cache: false
    dataset_cache_file: None
    num_cols: None
    consecutive_slices: 3
    segmentation_classes: 4
    data_saved_per_slice: false
    apply_prewhitening: false
    apply_gcc: false
    coil_combination_method: SENSE
    dimensionality: 2
    mask_args:
      type: none
      shift_mask: false
      use_seed: true
    half_scan_percentage: 0.0
    remask: false
    crop_size: None
    kspace_crop: false
    crop_before_masking: true
    kspace_zero_filling_size: None
    normalize_inputs: true
    max_norm: true
    fft_centered: false
    fft_normalization: backward
    spatial_dims:
      - -2
      - -1
    coil_dim: 2
    use_seed: true
    shuffle: false
    num_workers: 8
    drop_last: false
    pin_memory: false

  optim:
    name: adam
    lr: 1e-3
    betas:
      - 0.9
      - 0.98
    weight_decay: 0.0
    sched:
      name: InverseSquareRootAnnealing
      min_lr: 0.0
      last_epoch: -1
      warmup_ratio: 0.1

trainer:
  strategy: ddp
  gpus: 1
  num_nodes: 1
  max_epochs: 200
  precision: 16
  enable_checkpointing: false
  logger: false
  log_every_n_steps: 50
  check_val_every_n_epoch: -1
  max_steps: -1

exp_manager:
  exp_dir: ???
  create_tensorboard_logger: true
  create_wandb_logger: false
  wandb_logger_kwargs:
    project: ???
  files_to_copy: [ ]
