# coding=utf-8
# Automatically generated by Pynguin.
import mridc.utils.app_state as module_0


def test_case_0():
    try:
        app_state_0 = module_0.AppState()
        assert app_state_0.model_parallel_rank is None
        app_state_1 = module_0.AppState()
        assert app_state_1.model_parallel_rank is None
        var_0 = app_state_1.reset_model_guid_registry()
        var_1 = app_state_1.reset_model_guid_registry()
        str_0 = "JpcX/nu}J_ji/DY.e+"
        app_state_2 = module_0.AppState()
        assert app_state_2.model_parallel_rank is None
        model_metadata_registry_0 = app_state_2.get_model_metadata_from_guid(
            str_0)
    except BaseException:
        pass


def test_case_1():
    try:
        app_state_0 = module_0.AppState()
        assert app_state_0.model_parallel_rank is None
        app_state_1 = module_0.AppState()
        assert app_state_1.model_parallel_rank is None
        var_0 = app_state_1.reset_model_guid_registry()
        float_0 = -1878.58
        model_metadata_registry_0 = app_state_0.get_model_metadata_from_guid(
            float_0)
    except BaseException:
        pass


def test_case_2():
    try:
        list_0 = None
        app_state_0 = module_0.AppState()
        assert app_state_0.model_parallel_rank is None
        var_0 = app_state_0.reset_model_guid_registry()
        var_1 = app_state_0.reset_model_guid_registry()
        str_0 = "7>(uv=4#]L\tZTd@OOLx)"
        var_2 = app_state_0.register_model_guid(str_0)
        assert var_0 is None
        assert var_1 is None
        assert var_2 is None
        bool_0 = None
        tuple_0 = bool_0, list_0
        int_0 = 1391
        tuple_1 = app_state_0, tuple_0, int_0
        model_metadata_registry_0 = app_state_0.get_model_metadata_from_guid(
            tuple_1)
    except BaseException:
        pass


def test_case_3():
    try:
        str_0 = "im{m.BgC|zaB4BSU{A"
        app_state_0 = module_0.AppState()
        assert app_state_0.model_parallel_rank is None
        var_0 = app_state_0.register_model_guid(str_0)
        assert var_0 is None
        str_1 = None
        app_state_1 = module_0.AppState()
        assert app_state_1.model_parallel_rank is None
        var_1 = app_state_1.register_model_guid(str_1)
        assert var_1 is None
        app_state_2 = module_0.AppState()
        assert app_state_2.model_parallel_rank is None
        app_state_3 = module_0.AppState()
        assert app_state_3.model_parallel_rank is None
        model_metadata_registry_0 = app_state_3.get_model_metadata_from_guid(
            str_1)
        assert model_metadata_registry_0.guid is None
        assert model_metadata_registry_0.restoration_path is None
        assert module_0.ModelMetadataRegistry.restoration_path is None
        str_2 = "adamw"
        app_state_4 = module_0.AppState()
        assert app_state_4.model_parallel_rank is None
        var_2 = app_state_4.register_model_guid(str_2)
        assert var_2 is None
        float_0 = -2119.8085
        model_metadata_registry_1 = app_state_4.get_model_metadata_from_guid(
            float_0)
    except BaseException:
        pass


def test_case_4():
    try:
        str_0 = None
        str_1 = "+ \r?pBuY2:[G:WM_)&s"
        app_state_0 = module_0.AppState()
        assert app_state_0.model_parallel_rank is None
        var_0 = app_state_0.register_model_guid(str_0, str_1)
        assert var_0 is None
        int_0 = 32
        app_state_1 = module_0.AppState()
        assert app_state_1.model_parallel_rank is None
        model_metadata_registry_0 = app_state_1.get_model_metadata_from_guid(
            int_0)
    except BaseException:
        pass


def test_case_5():
    try:
        app_state_0 = module_0.AppState()
        assert app_state_0.model_parallel_rank is None
        str_0 = "DPWyC`j7.\x0btyXxu"
        var_0 = app_state_0.register_model_guid(str_0, str_0)
        assert var_0 is None
        var_1 = app_state_0.reset_model_guid_registry()
        assert var_1 is None
        list_0 = [var_1]
        model_metadata_registry_0 = app_state_0.get_model_metadata_from_guid(
            list_0)
    except BaseException:
        pass


def test_case_6():
    try:
        str_0 = "MV\tT'wGU*B\r{lP9vwn\n"
        app_state_0 = module_0.AppState()
        assert app_state_0.model_parallel_rank is None
        var_0 = app_state_0.register_model_guid(str_0)
        assert var_0 is None
        str_1 = "fz\x0cM|CTO2SDH!"
        app_state_1 = module_0.AppState()
        assert app_state_1.model_parallel_rank is None
        model_metadata_registry_0 = app_state_1.get_model_metadata_from_guid(
            str_1)
    except BaseException:
        pass
