# coding=utf-8
# Automatically generated by Pynguin.
import mridc.core.conf.dataloader as module_0


def test_case_0():
    try:
        int_0 = -1238
        data_loader_config_0 = module_0.DataLoaderConfig(int_0, int_0)
        assert data_loader_config_0.batch_size == -1238
        assert data_loader_config_0.shuffle == -1238
        assert data_loader_config_0.sampler is None
        assert data_loader_config_0.batch_sampler is None
        assert data_loader_config_0.num_workers == 0
        assert data_loader_config_0.collate_fn is None
        assert data_loader_config_0.pin_memory is False
        assert data_loader_config_0.drop_last is False
        assert data_loader_config_0.timeout == 0
        assert data_loader_config_0.worker_init_fn is None
        assert data_loader_config_0.multiprocessing_context is None
        assert module_0.DataLoaderConfig.batch_size == "???"
        assert module_0.DataLoaderConfig.shuffle is False
        assert module_0.DataLoaderConfig.sampler is None
        assert module_0.DataLoaderConfig.batch_sampler is None
        assert module_0.DataLoaderConfig.num_workers == 0
        assert module_0.DataLoaderConfig.collate_fn is None
        assert module_0.DataLoaderConfig.pin_memory is False
        assert module_0.DataLoaderConfig.drop_last is False
        assert module_0.DataLoaderConfig.timeout == 0
        assert module_0.DataLoaderConfig.worker_init_fn is None
        assert module_0.DataLoaderConfig.multiprocessing_context is None
        int_1 = 2700
        bool_0 = False
        int_2 = 4734
        data_loader_config_1 = module_0.DataLoaderConfig(int_1, bool_0, int_2)
        assert data_loader_config_1.batch_size == 2700
        assert data_loader_config_1.shuffle is False
        assert data_loader_config_1.sampler == 4734
        assert data_loader_config_1.batch_sampler is None
        assert data_loader_config_1.num_workers == 0
        assert data_loader_config_1.collate_fn is None
        assert data_loader_config_1.pin_memory is False
        assert data_loader_config_1.drop_last is False
        assert data_loader_config_1.timeout == 0
        assert data_loader_config_1.worker_init_fn is None
        assert data_loader_config_1.multiprocessing_context is None
        int_3 = 4298
        data_loader_config_2 = module_0.DataLoaderConfig(int_3)
        assert data_loader_config_2.batch_size == 4298
        assert data_loader_config_2.shuffle is False
        assert data_loader_config_2.sampler is None
        assert data_loader_config_2.batch_sampler is None
        assert data_loader_config_2.num_workers == 0
        assert data_loader_config_2.collate_fn is None
        assert data_loader_config_2.pin_memory is False
        assert data_loader_config_2.drop_last is False
        assert data_loader_config_2.timeout == 0
        assert data_loader_config_2.worker_init_fn is None
        assert data_loader_config_2.multiprocessing_context is None
        data_loader_config_3 = module_0.DataLoaderConfig(bool_0, int_3)
        assert data_loader_config_3.batch_size is False
        assert data_loader_config_3.shuffle == 4298
        assert data_loader_config_3.sampler is None
        assert data_loader_config_3.batch_sampler is None
        assert data_loader_config_3.num_workers == 0
        assert data_loader_config_3.collate_fn is None
        assert data_loader_config_3.pin_memory is False
        assert data_loader_config_3.drop_last is False
        assert data_loader_config_3.timeout == 0
        assert data_loader_config_3.worker_init_fn is None
        assert data_loader_config_3.multiprocessing_context is None
        bool_1 = False
        data_loader_config_4 = module_0.DataLoaderConfig(int_2, bool_1, int_0)
        assert data_loader_config_4.batch_size == 4734
        assert data_loader_config_4.shuffle is False
        assert data_loader_config_4.sampler == -1238
        assert data_loader_config_4.batch_sampler is None
        assert data_loader_config_4.num_workers == 0
        assert data_loader_config_4.collate_fn is None
        assert data_loader_config_4.pin_memory is False
        assert data_loader_config_4.drop_last is False
        assert data_loader_config_4.timeout == 0
        assert data_loader_config_4.worker_init_fn is None
        assert data_loader_config_4.multiprocessing_context is None
    except BaseException:
        pass


def test_case_1():
    try:
        bool_0 = False
        int_0 = 641
        bool_1 = True
        data_loader_config_0 = module_0.DataLoaderConfig(bool_0, int_0, bool_1)
        assert data_loader_config_0.batch_size is False
        assert data_loader_config_0.shuffle == 641
        assert data_loader_config_0.sampler is True
        assert data_loader_config_0.batch_sampler is None
        assert data_loader_config_0.num_workers == 0
        assert data_loader_config_0.collate_fn is None
        assert data_loader_config_0.pin_memory is False
        assert data_loader_config_0.drop_last is False
        assert data_loader_config_0.timeout == 0
        assert data_loader_config_0.worker_init_fn is None
        assert data_loader_config_0.multiprocessing_context is None
        assert module_0.DataLoaderConfig.batch_size == "???"
        assert module_0.DataLoaderConfig.shuffle is False
        assert module_0.DataLoaderConfig.sampler is None
        assert module_0.DataLoaderConfig.batch_sampler is None
        assert module_0.DataLoaderConfig.num_workers == 0
        assert module_0.DataLoaderConfig.collate_fn is None
        assert module_0.DataLoaderConfig.pin_memory is False
        assert module_0.DataLoaderConfig.drop_last is False
        assert module_0.DataLoaderConfig.timeout == 0
        assert module_0.DataLoaderConfig.worker_init_fn is None
        assert module_0.DataLoaderConfig.multiprocessing_context is None
        int_1 = None
        bool_2 = False
        any_0 = None
        data_loader_config_1 = module_0.DataLoaderConfig(int_1, bool_2, int_1, any_0)
        assert data_loader_config_1.batch_size is None
        assert data_loader_config_1.shuffle is False
        assert data_loader_config_1.sampler is None
        assert data_loader_config_1.batch_sampler is None
        assert data_loader_config_1.num_workers == 0
        assert data_loader_config_1.collate_fn is None
        assert data_loader_config_1.pin_memory is False
        assert data_loader_config_1.drop_last is False
        assert data_loader_config_1.timeout == 0
        assert data_loader_config_1.worker_init_fn is None
        assert data_loader_config_1.multiprocessing_context is None
    except BaseException:
        pass
