# coding=utf-8
# Automatically generated by Pynguin.
import mridc.collections.reconstruction.models.primaldual.pd as module_0


def test_case_0():
    try:
        bool_0 = False
        dual_net_0 = module_0.DualNet(bool_0)
    except BaseException:
        pass


def test_case_1():
    try:
        bool_0 = True
        dual_net_0 = module_0.DualNet(bool_0)
    except BaseException:
        pass


def test_case_2():
    try:
        bytes_0 = b"\x83\xf2\xdfd\xd2n\xcd\xdc\xcc\xfe"
        dual_net_0 = module_0.DualNet(bytes_0)
    except BaseException:
        pass


def test_case_3():
    try:
        str_0 = "lug`e_m|a}.H-W7V{fu\r"
        dict_0 = {str_0: str_0, str_0: str_0, str_0: str_0}
        primal_net_0 = module_0.PrimalNet(dict_0)
    except BaseException:
        pass


def test_case_4():
    try:
        dict_0 = {}
        dual_net_0 = module_0.DualNet(dict_0)
    except BaseException:
        pass


def test_case_5():
    try:
        str_0 = "B;!@"
        primal_net_0 = module_0.PrimalNet(str_0)
    except BaseException:
        pass


def test_case_6():
    try:
        bool_0 = False
        dual_net_0 = module_0.DualNet(bool_0)
    except BaseException:
        pass


def test_case_7():
    try:
        bool_0 = False
        primal_net_0 = module_0.PrimalNet(bool_0)
    except BaseException:
        pass
