# coding=utf-8
# Automatically generated by Pynguin.
import mridc.core.optim.optimizer_with_master_params as module_0


def test_case_0():
    try:
        bool_0 = False
        bytes_0 = b".|\xd2\x82\x99'\xfaIB\xbe$Xf\xebX\xfc\x1f\x0b\xa7"
        grad_bucket_0 = module_0.GradBucket(bool_0, bytes_0)
    except BaseException:
        pass


def test_case_1():
    try:
        str_0 = "^1D8&AV(,"
        main_params_optimizer_wrapper_0 = None
        grad_bucket_0 = module_0.GradBucket(
            str_0, main_params_optimizer_wrapper_0)
    except BaseException:
        pass


def test_case_2():
    try:
        set_0 = set()
        tuple_0 = ()
        grad_bucket_0 = module_0.GradBucket(tuple_0, set_0)
    except BaseException:
        pass


def test_case_3():
    try:
        int_0 = 9
        float_0 = 1918.66
        grad_bucket_0 = module_0.GradBucket(int_0, float_0)
    except BaseException:
        pass


def test_case_4():
    try:
        bytes_0 = b"R\xc3\x960\x8e\xa3'Z"
        str_0 = None
        tuple_0 = None
        int_0 = None
        tuple_1 = str_0, bytes_0, tuple_0, int_0
        int_1 = -1442
        grad_bucket_0 = module_0.GradBucket(tuple_1, int_1)
    except BaseException:
        pass


def test_case_6():
    try:
        int_0 = 1301
        str_0 = '!F!\rSe1q$"yAtW&:^dNw'
        grad_bucket_0 = module_0.GradBucket(int_0, str_0)
    except BaseException:
        pass


def test_case_8():
    try:
        int_0 = 100
        float_0 = 8.1
        grad_bucket_0 = module_0.GradBucket(int_0, float_0)
    except BaseException:
        pass


def test_case_9():
    try:
        str_0 = "%M"
        main_params_optimizer_wrapper_0 = module_0.MainParamsOptimizerWrapper(
            str_0)
    except BaseException:
        pass
