# coding=utf-8
# Automatically generated by Pynguin.
import os as module_1
import pathlib as module_2

import mridc.collections.segmentation.data.mri_data as module_0


def test_case_0():
    try:
        str_0 = "cuda"
        float_0 = -1128.125
        int_0 = 713
        tuple_0 = (int_0,)
        j_r_s_m_r_i_slice_dataset_0 = module_0.JRSMRISliceDataset(
            str_0, str_0, float_0, str_0, tuple_0)
    except BaseException:
        pass


def test_case_1():
    try:
        path_like_0 = module_1.PathLike()
    except BaseException:
        pass


def test_case_2():
    try:
        str_0 = '8sP"w+:mI'
        bool_0 = False
        j_r_s_m_r_i_slice_dataset_0 = module_0.JRSMRISliceDataset(
            str_0, str_0, bool_0)
    except BaseException:
        pass


def test_case_3():
    try:
        str_0 = """
        Parameters
        ----------
        image: Input 4D tensor of shape `(N, in_chans, H, W)`.

        Returns
        -------
        Output tensor of shape `(N, out_chans, H*2, W*2)`.
        """
        path_0 = module_2.Path()
        path_1 = module_2.Path()
        bool_0 = True
        int_0 = None
        bool_1 = True
        str_1 = "`E9:@}N&Ufdf|"
        j_r_s_m_r_i_slice_dataset_0 = module_0.JRSMRISliceDataset(
            path_0, path_1, bool_0, str_0, int_0, bool_1, str_1)
    except BaseException:
        pass


def test_case_4():
    try:
        path_like_0 = module_1.PathLike()
    except BaseException:
        pass


def test_case_5():
    try:
        path_0 = module_2.Path()
        bool_0 = True
        j_r_s_m_r_i_slice_dataset_0 = module_0.JRSMRISliceDataset(
            path_0, path_0, path_0, bool_0)
    except BaseException:
        pass


def test_case_6():
    try:
        str_0 = "Vm4o&r$"
        str_1 = 'W6PT";p20UQn'
        bytes_0 = b"\x0c\xf2\xf5\xf5\x85\xa6\x92\xe3\x9c\x90\xf3\xe1J"
        str_2 = "#T;3!w\x0cxDt#"
        dict_0 = {str_0: str_0, str_1: bytes_0, str_1: str_1, str_2: str_1}
        path_0 = module_2.Path(**dict_0)
        path_like_0 = module_1.PathLike(**dict_0)
    except BaseException:
        pass


def test_case_7():
    try:
        str_0 = "^q`4N2rgP4^u|?fG"
        int_0 = 37
        float_0 = 71.667
        int_1 = -1069
        j_r_s_m_r_i_slice_dataset_0 = module_0.JRSMRISliceDataset(
            str_0, float_0, int_1, int_0)
    except BaseException:
        pass


def test_case_8():
    try:
        str_0 = "#>3bk\\!J1"
        none_type_0 = None
        int_0 = -672
        bool_0 = True
        j_r_s_m_r_i_slice_dataset_0 = module_0.JRSMRISliceDataset(
            str_0, str_0, none_type_0, int_0, int_0, bool_0)
    except BaseException:
        pass


def test_case_9():
    try:
        path_0 = module_2.Path()
        float_0 = 660.925
        j_r_s_m_r_i_slice_dataset_0 = module_0.JRSMRISliceDataset(
            path_0, path_0, float_0)
    except BaseException:
        pass
