# coding=utf-8
# Automatically generated by Pynguin.
import pytest

import mridc.core.conf.dataloader as module_0


def test_case_0():
    float_0 = 1757.33
    bool_0 = None
    int_0 = 103
    var_0 = None
    int_1 = 4913
    data_loader_config_0 = module_0.DataLoaderConfig(
        bool_0, var_0, int_1, bool_0, bool_0)
    assert data_loader_config_0.batch_size is None
    assert data_loader_config_0.shuffle is None
    assert data_loader_config_0.sampler == 4913
    assert data_loader_config_0.batch_sampler is None
    assert data_loader_config_0.num_workers is None
    assert data_loader_config_0.collate_fn is None
    assert data_loader_config_0.pin_memory is False
    assert data_loader_config_0.drop_last is False
    assert data_loader_config_0.timeout == 0
    assert data_loader_config_0.worker_init_fn is None
    assert data_loader_config_0.multiprocessing_context is None
    assert module_0.DataLoaderConfig.batch_size == "???"
    assert module_0.DataLoaderConfig.shuffle is False
    assert module_0.DataLoaderConfig.sampler is None
    assert module_0.DataLoaderConfig.batch_sampler is None
    assert module_0.DataLoaderConfig.num_workers == 0
    assert module_0.DataLoaderConfig.collate_fn is None
    assert module_0.DataLoaderConfig.pin_memory is False
    assert module_0.DataLoaderConfig.drop_last is False
    assert module_0.DataLoaderConfig.timeout == 0
    assert module_0.DataLoaderConfig.worker_init_fn is None
    assert module_0.DataLoaderConfig.multiprocessing_context is None
    data_loader_config_1 = module_0.DataLoaderConfig(float_0, bool_0, int_0)
    assert data_loader_config_1.batch_size == pytest.approx(
        1757.33, abs=0.01, rel=0.01)
    assert data_loader_config_1.shuffle is None
    assert data_loader_config_1.sampler == 103
    assert data_loader_config_1.batch_sampler is None
    assert data_loader_config_1.num_workers == 0
    assert data_loader_config_1.collate_fn is None
    assert data_loader_config_1.pin_memory is False
    assert data_loader_config_1.drop_last is False
    assert data_loader_config_1.timeout == 0
    assert data_loader_config_1.worker_init_fn is None
    assert data_loader_config_1.multiprocessing_context is None


def test_case_1():
    bool_0 = False
    var_0 = None
    list_0 = []
    int_0 = None
    str_0 = "NH#|N/whu]n"
    float_0 = 1978.9
    bool_1 = True
    var_1 = None
    data_loader_config_0 = module_0.DataLoaderConfig(
        int_0, str_0, float_0, bool_1, var_1)
    assert data_loader_config_0.batch_size is None
    assert data_loader_config_0.shuffle == "NH#|N/whu]n"
    assert data_loader_config_0.sampler == pytest.approx(
        1978.9, abs=0.01, rel=0.01)
    assert data_loader_config_0.batch_sampler is True
    assert data_loader_config_0.num_workers is None
    assert data_loader_config_0.collate_fn is None
    assert data_loader_config_0.pin_memory is False
    assert data_loader_config_0.drop_last is False
    assert data_loader_config_0.timeout == 0
    assert data_loader_config_0.worker_init_fn is None
    assert data_loader_config_0.multiprocessing_context is None
    assert module_0.DataLoaderConfig.batch_size == "???"
    assert module_0.DataLoaderConfig.shuffle is False
    assert module_0.DataLoaderConfig.sampler is None
    assert module_0.DataLoaderConfig.batch_sampler is None
    assert module_0.DataLoaderConfig.num_workers == 0
    assert module_0.DataLoaderConfig.collate_fn is None
    assert module_0.DataLoaderConfig.pin_memory is False
    assert module_0.DataLoaderConfig.drop_last is False
    assert module_0.DataLoaderConfig.timeout == 0
    assert module_0.DataLoaderConfig.worker_init_fn is None
    assert module_0.DataLoaderConfig.multiprocessing_context is None
    var_2 = None
    data_loader_config_1 = module_0.DataLoaderConfig(
        bool_0, var_0, bool_0, list_0, var_2)
    assert data_loader_config_1.batch_size is False
    assert data_loader_config_1.shuffle is None
    assert data_loader_config_1.sampler is False
    assert data_loader_config_1.batch_sampler == []
    assert data_loader_config_1.num_workers is None
    assert data_loader_config_1.collate_fn is None
    assert data_loader_config_1.pin_memory is False
    assert data_loader_config_1.drop_last is False
    assert data_loader_config_1.timeout == 0
    assert data_loader_config_1.worker_init_fn is None
    assert data_loader_config_1.multiprocessing_context is None
