# coding=utf-8
# Automatically generated by Pynguin.
import mridc.collections.common.parts.training_utils as module_0


def test_case_0():
    var_0 = module_0.avoid_float16_autocast_context()
    assert var_0.enter_result is None
    var_1 = module_0.avoid_float16_autocast_context()
    assert var_1.enter_result is None
    var_2 = module_0.avoid_bfloat16_autocast_context()
    assert var_2.enter_result is None
    var_3 = module_0.avoid_float16_autocast_context()
    assert var_3.enter_result is None
    var_4 = module_0.avoid_float16_autocast_context()
    assert var_4.enter_result is None
    var_5 = module_0.avoid_bfloat16_autocast_context()
    assert var_5.enter_result is None
    var_6 = module_0.avoid_bfloat16_autocast_context()
    assert var_6.enter_result is None
    var_7 = module_0.avoid_bfloat16_autocast_context()
    assert var_7.enter_result is None
    var_8 = module_0.avoid_bfloat16_autocast_context()
    assert var_8.enter_result is None
    var_9 = module_0.avoid_float16_autocast_context()
    assert var_9.enter_result is None
    var_10 = module_0.avoid_float16_autocast_context()
    assert var_10.enter_result is None
    var_11 = module_0.avoid_float16_autocast_context()
    assert var_11.enter_result is None
    var_12 = module_0.avoid_bfloat16_autocast_context()
    assert var_12.enter_result is None
    var_13 = module_0.avoid_float16_autocast_context()
    assert var_13.enter_result is None
    var_14 = module_0.avoid_bfloat16_autocast_context()
    assert var_14.enter_result is None
    var_15 = module_0.avoid_bfloat16_autocast_context()
    assert var_15.enter_result is None
    var_16 = module_0.avoid_float16_autocast_context()
    assert var_16.enter_result is None
    var_17 = module_0.avoid_float16_autocast_context()
    assert var_17.enter_result is None
    var_18 = module_0.avoid_bfloat16_autocast_context()
    assert var_18.enter_result is None
    var_19 = module_0.avoid_bfloat16_autocast_context()
    assert var_19.enter_result is None
    var_20 = module_0.avoid_float16_autocast_context()
    assert var_20.enter_result is None
    var_21 = module_0.avoid_float16_autocast_context()
    assert var_21.enter_result is None
    var_22 = module_0.avoid_bfloat16_autocast_context()
    assert var_22.enter_result is None
    var_23 = module_0.avoid_bfloat16_autocast_context()
    assert var_23.enter_result is None
    var_24 = module_0.avoid_float16_autocast_context()
    assert var_24.enter_result is None
    var_25 = module_0.avoid_bfloat16_autocast_context()
    assert var_25.enter_result is None
    var_26 = module_0.avoid_float16_autocast_context()
    assert var_26.enter_result is None
    var_27 = module_0.avoid_float16_autocast_context()
    assert var_27.enter_result is None
    var_28 = module_0.avoid_float16_autocast_context()
    assert var_28.enter_result is None
    var_29 = module_0.avoid_bfloat16_autocast_context()
    assert var_29.enter_result is None
    var_30 = module_0.avoid_bfloat16_autocast_context()
    assert var_30.enter_result is None
    var_31 = module_0.avoid_float16_autocast_context()
    assert var_31.enter_result is None
    var_32 = module_0.avoid_bfloat16_autocast_context()
    assert var_32.enter_result is None
    var_33 = module_0.avoid_float16_autocast_context()
    assert var_33.enter_result is None
    var_34 = module_0.avoid_float16_autocast_context()
    assert var_34.enter_result is None
    var_35 = module_0.avoid_bfloat16_autocast_context()
    assert var_35.enter_result is None


def test_case_1():
    var_0 = module_0.avoid_float16_autocast_context()
    assert var_0.enter_result is None
    var_1 = module_0.avoid_float16_autocast_context()
    assert var_1.enter_result is None
    var_2 = module_0.avoid_float16_autocast_context()
    assert var_2.enter_result is None
    var_3 = module_0.avoid_bfloat16_autocast_context()
    assert var_3.enter_result is None
    var_4 = module_0.avoid_float16_autocast_context()
    assert var_4.enter_result is None
    var_5 = module_0.avoid_bfloat16_autocast_context()
    assert var_5.enter_result is None
    var_6 = module_0.avoid_float16_autocast_context()
    assert var_6.enter_result is None
    var_7 = module_0.avoid_float16_autocast_context()
    assert var_7.enter_result is None
    var_8 = module_0.avoid_float16_autocast_context()
    assert var_8.enter_result is None


def test_case_2():
    var_0 = module_0.avoid_float16_autocast_context()
    assert var_0.enter_result is None
    var_1 = module_0.avoid_bfloat16_autocast_context()
    assert var_1.enter_result is None
    var_2 = module_0.avoid_float16_autocast_context()
    assert var_2.enter_result is None


def test_case_3():
    var_0 = module_0.avoid_float16_autocast_context()
    assert var_0.enter_result is None
    var_1 = module_0.avoid_bfloat16_autocast_context()
    assert var_1.enter_result is None
    var_2 = module_0.avoid_float16_autocast_context()
    assert var_2.enter_result is None
    var_3 = module_0.avoid_bfloat16_autocast_context()
    assert var_3.enter_result is None
    var_4 = module_0.avoid_float16_autocast_context()
    assert var_4.enter_result is None
    var_5 = module_0.avoid_bfloat16_autocast_context()
    assert var_5.enter_result is None
    var_6 = module_0.avoid_float16_autocast_context()
    assert var_6.enter_result is None
    var_7 = module_0.avoid_bfloat16_autocast_context()
    assert var_7.enter_result is None
    var_8 = module_0.avoid_bfloat16_autocast_context()
    assert var_8.enter_result is None
    var_9 = module_0.avoid_float16_autocast_context()
    assert var_9.enter_result is None
    var_10 = module_0.avoid_bfloat16_autocast_context()
    assert var_10.enter_result is None
    var_11 = module_0.avoid_float16_autocast_context()
    assert var_11.enter_result is None
    var_12 = module_0.avoid_float16_autocast_context()
    assert var_12.enter_result is None
    var_13 = module_0.avoid_float16_autocast_context()
    assert var_13.enter_result is None
    var_14 = module_0.avoid_bfloat16_autocast_context()
    assert var_14.enter_result is None
    var_15 = module_0.avoid_bfloat16_autocast_context()
    assert var_15.enter_result is None
    var_16 = module_0.avoid_float16_autocast_context()
    assert var_16.enter_result is None
    var_17 = module_0.avoid_bfloat16_autocast_context()
    assert var_17.enter_result is None
    var_18 = module_0.avoid_bfloat16_autocast_context()
    assert var_18.enter_result is None
    var_19 = module_0.avoid_float16_autocast_context()
    assert var_19.enter_result is None
    var_20 = module_0.avoid_bfloat16_autocast_context()
    assert var_20.enter_result is None
    var_21 = module_0.avoid_bfloat16_autocast_context()
    assert var_21.enter_result is None
    var_22 = module_0.avoid_bfloat16_autocast_context()
    assert var_22.enter_result is None
    var_23 = module_0.avoid_bfloat16_autocast_context()
    assert var_23.enter_result is None
    var_24 = module_0.avoid_float16_autocast_context()
    assert var_24.enter_result is None
    var_25 = module_0.avoid_bfloat16_autocast_context()
    assert var_25.enter_result is None
    var_26 = module_0.avoid_bfloat16_autocast_context()
    assert var_26.enter_result is None
    var_27 = module_0.avoid_float16_autocast_context()
    assert var_27.enter_result is None
    var_28 = module_0.avoid_float16_autocast_context()
    assert var_28.enter_result is None
    var_29 = module_0.avoid_float16_autocast_context()
    assert var_29.enter_result is None
    var_30 = module_0.avoid_bfloat16_autocast_context()
    assert var_30.enter_result is None
    var_31 = module_0.avoid_bfloat16_autocast_context()
    assert var_31.enter_result is None
    var_32 = module_0.avoid_bfloat16_autocast_context()
    assert var_32.enter_result is None
    var_33 = module_0.avoid_bfloat16_autocast_context()
    assert var_33.enter_result is None


def test_case_4():
    var_0 = module_0.avoid_bfloat16_autocast_context()
    assert var_0.enter_result is None
    var_1 = module_0.avoid_bfloat16_autocast_context()
    assert var_1.enter_result is None
    var_2 = module_0.avoid_bfloat16_autocast_context()
    assert var_2.enter_result is None
    var_3 = module_0.avoid_float16_autocast_context()
    assert var_3.enter_result is None
    var_4 = module_0.avoid_float16_autocast_context()
    assert var_4.enter_result is None
    var_5 = module_0.avoid_float16_autocast_context()
    assert var_5.enter_result is None
    var_6 = module_0.avoid_bfloat16_autocast_context()
    assert var_6.enter_result is None
    var_7 = module_0.avoid_bfloat16_autocast_context()
    assert var_7.enter_result is None
    var_8 = module_0.avoid_bfloat16_autocast_context()
    assert var_8.enter_result is None
    var_9 = module_0.avoid_float16_autocast_context()
    assert var_9.enter_result is None
    var_10 = module_0.avoid_float16_autocast_context()
    assert var_10.enter_result is None
    var_11 = module_0.avoid_bfloat16_autocast_context()
    assert var_11.enter_result is None
    var_12 = module_0.avoid_float16_autocast_context()
    assert var_12.enter_result is None
    var_13 = module_0.avoid_bfloat16_autocast_context()
    assert var_13.enter_result is None
    var_14 = module_0.avoid_bfloat16_autocast_context()
    assert var_14.enter_result is None
    var_15 = module_0.avoid_float16_autocast_context()
    assert var_15.enter_result is None
    var_16 = module_0.avoid_float16_autocast_context()
    assert var_16.enter_result is None
    var_17 = module_0.avoid_bfloat16_autocast_context()
    assert var_17.enter_result is None
    var_18 = module_0.avoid_bfloat16_autocast_context()
    assert var_18.enter_result is None
    var_19 = module_0.avoid_float16_autocast_context()
    assert var_19.enter_result is None
    var_20 = module_0.avoid_float16_autocast_context()
    assert var_20.enter_result is None
    var_21 = module_0.avoid_bfloat16_autocast_context()
    assert var_21.enter_result is None
    var_22 = module_0.avoid_float16_autocast_context()
    assert var_22.enter_result is None
    var_23 = module_0.avoid_float16_autocast_context()
    assert var_23.enter_result is None
    var_24 = module_0.avoid_float16_autocast_context()
    assert var_24.enter_result is None
    var_25 = module_0.avoid_float16_autocast_context()
    assert var_25.enter_result is None
    var_26 = module_0.avoid_float16_autocast_context()
    assert var_26.enter_result is None
    var_27 = module_0.avoid_bfloat16_autocast_context()
    assert var_27.enter_result is None
    var_28 = module_0.avoid_float16_autocast_context()
    assert var_28.enter_result is None
    var_29 = module_0.avoid_bfloat16_autocast_context()
    assert var_29.enter_result is None
    var_30 = module_0.avoid_bfloat16_autocast_context()
    assert var_30.enter_result is None


def test_case_5():
    var_0 = module_0.avoid_bfloat16_autocast_context()
    assert var_0.enter_result is None
    var_1 = module_0.avoid_float16_autocast_context()
    assert var_1.enter_result is None
    var_2 = module_0.avoid_bfloat16_autocast_context()
    assert var_2.enter_result is None
    var_3 = module_0.avoid_float16_autocast_context()
    assert var_3.enter_result is None
    var_4 = module_0.avoid_float16_autocast_context()
    assert var_4.enter_result is None
    var_5 = module_0.avoid_bfloat16_autocast_context()
    assert var_5.enter_result is None
    var_6 = module_0.avoid_float16_autocast_context()
    assert var_6.enter_result is None
    var_7 = module_0.avoid_bfloat16_autocast_context()
    assert var_7.enter_result is None
    var_8 = module_0.avoid_float16_autocast_context()
    assert var_8.enter_result is None
    var_9 = module_0.avoid_bfloat16_autocast_context()
    assert var_9.enter_result is None
    var_10 = module_0.avoid_bfloat16_autocast_context()
    assert var_10.enter_result is None
    var_11 = module_0.avoid_bfloat16_autocast_context()
    assert var_11.enter_result is None
    var_12 = module_0.avoid_float16_autocast_context()
    assert var_12.enter_result is None
    var_13 = module_0.avoid_bfloat16_autocast_context()
    assert var_13.enter_result is None
    var_14 = module_0.avoid_bfloat16_autocast_context()
    assert var_14.enter_result is None
    var_15 = module_0.avoid_float16_autocast_context()
    assert var_15.enter_result is None
    var_16 = module_0.avoid_float16_autocast_context()
    assert var_16.enter_result is None
    var_17 = module_0.avoid_float16_autocast_context()
    assert var_17.enter_result is None
    var_18 = module_0.avoid_float16_autocast_context()
    assert var_18.enter_result is None
    var_19 = module_0.avoid_bfloat16_autocast_context()
    assert var_19.enter_result is None
    var_20 = module_0.avoid_bfloat16_autocast_context()
    assert var_20.enter_result is None
    var_21 = module_0.avoid_float16_autocast_context()
    assert var_21.enter_result is None
    var_22 = module_0.avoid_bfloat16_autocast_context()
    assert var_22.enter_result is None
    var_23 = module_0.avoid_float16_autocast_context()
    assert var_23.enter_result is None
    var_24 = module_0.avoid_float16_autocast_context()
    assert var_24.enter_result is None
    var_25 = module_0.avoid_float16_autocast_context()
    assert var_25.enter_result is None
    var_26 = module_0.avoid_bfloat16_autocast_context()
    assert var_26.enter_result is None
    var_27 = module_0.avoid_bfloat16_autocast_context()
    assert var_27.enter_result is None
    var_28 = module_0.avoid_bfloat16_autocast_context()
    assert var_28.enter_result is None
    var_29 = module_0.avoid_float16_autocast_context()
    assert var_29.enter_result is None
    var_30 = module_0.avoid_float16_autocast_context()
    assert var_30.enter_result is None
    var_31 = module_0.avoid_float16_autocast_context()
    assert var_31.enter_result is None
    var_32 = module_0.avoid_bfloat16_autocast_context()
    assert var_32.enter_result is None
    var_33 = module_0.avoid_float16_autocast_context()
    assert var_33.enter_result is None
    var_34 = module_0.avoid_bfloat16_autocast_context()
    assert var_34.enter_result is None
    var_35 = module_0.avoid_float16_autocast_context()
    assert var_35.enter_result is None
    var_36 = module_0.avoid_float16_autocast_context()
    assert var_36.enter_result is None


def test_case_6():
    var_0 = module_0.avoid_float16_autocast_context()
    assert var_0.enter_result is None
    var_1 = module_0.avoid_bfloat16_autocast_context()
    assert var_1.enter_result is None
    var_2 = module_0.avoid_bfloat16_autocast_context()
    assert var_2.enter_result is None
    var_3 = module_0.avoid_float16_autocast_context()
    assert var_3.enter_result is None
    var_4 = module_0.avoid_float16_autocast_context()
    assert var_4.enter_result is None
    var_5 = module_0.avoid_bfloat16_autocast_context()
    assert var_5.enter_result is None
    var_6 = module_0.avoid_float16_autocast_context()
    assert var_6.enter_result is None
    var_7 = module_0.avoid_float16_autocast_context()
    assert var_7.enter_result is None
    var_8 = module_0.avoid_bfloat16_autocast_context()
    assert var_8.enter_result is None
    var_9 = module_0.avoid_bfloat16_autocast_context()
    assert var_9.enter_result is None
    var_10 = module_0.avoid_bfloat16_autocast_context()
    assert var_10.enter_result is None
    var_11 = module_0.avoid_float16_autocast_context()
    assert var_11.enter_result is None
    var_12 = module_0.avoid_bfloat16_autocast_context()
    assert var_12.enter_result is None


def test_case_7():
    var_0 = module_0.avoid_float16_autocast_context()
    assert var_0.enter_result is None
    var_1 = module_0.avoid_float16_autocast_context()
    assert var_1.enter_result is None
    var_2 = module_0.avoid_float16_autocast_context()
    assert var_2.enter_result is None
    var_3 = module_0.avoid_float16_autocast_context()
    assert var_3.enter_result is None
    var_4 = module_0.avoid_bfloat16_autocast_context()
    assert var_4.enter_result is None
    var_5 = module_0.avoid_bfloat16_autocast_context()
    assert var_5.enter_result is None
    var_6 = module_0.avoid_bfloat16_autocast_context()
    assert var_6.enter_result is None
    var_7 = module_0.avoid_float16_autocast_context()
    assert var_7.enter_result is None
    var_8 = module_0.avoid_bfloat16_autocast_context()
    assert var_8.enter_result is None
    var_9 = module_0.avoid_bfloat16_autocast_context()
    assert var_9.enter_result is None
    var_10 = module_0.avoid_bfloat16_autocast_context()
    assert var_10.enter_result is None
    var_11 = module_0.avoid_float16_autocast_context()
    assert var_11.enter_result is None


def test_case_8():
    var_0 = module_0.avoid_bfloat16_autocast_context()
    assert var_0.enter_result is None
    var_1 = module_0.avoid_bfloat16_autocast_context()
    assert var_1.enter_result is None
    var_2 = module_0.avoid_bfloat16_autocast_context()
    assert var_2.enter_result is None
    var_3 = module_0.avoid_bfloat16_autocast_context()
    assert var_3.enter_result is None
    var_4 = module_0.avoid_bfloat16_autocast_context()
    assert var_4.enter_result is None
    var_5 = module_0.avoid_float16_autocast_context()
    assert var_5.enter_result is None
    var_6 = module_0.avoid_bfloat16_autocast_context()
    assert var_6.enter_result is None
