# coding=utf-8
# Automatically generated by Pynguin.
import mridc.utils.get_rank as module_0


def test_case_0():
    var_0 = module_0.is_global_rank_zero()
    assert var_0 is True
    var_1 = module_0.get_rank()
    assert var_1 == 0
    var_2 = module_0.get_rank()
    assert var_2 == 0
    var_3 = module_0.get_rank()
    assert var_3 == 0
    var_4 = module_0.is_global_rank_zero()
    assert var_4 is True
    var_5 = module_0.is_global_rank_zero()
    assert var_5 is True
