# coding=utf-8
# Automatically generated by Pynguin.
import mridc.core.conf.hydra_runner as module_0


def test_case_0():
    try:
        float_0 = 343.877
        callable_0 = module_0.hydra_runner(float_0)
        str_0 = "Path of the files to be converted."
        callable_1 = module_0.hydra_runner(str_0)
    except BaseException:
        pass
