# coding=utf-8
# Automatically generated by Pynguin.
import mridc.core.conf.base_config as module_0


def test_case_0():
    try:
        config_0 = module_0.Config()
        assert config_0.name is None
        assert module_0.Config.name is None
        config_1 = module_0.Config()
        assert config_1.name is None
        config_2 = module_0.Config()
        assert config_2.name is None
        config_3 = module_0.Config()
        assert config_3.name is None
        config_4 = module_0.Config()
        assert config_4.name is None
        str_0 = '39~O{c=[0j$"'
        config_5 = module_0.Config(str_0)
        assert config_5.name == '39~O{c=[0j$"'
        str_1 = "MI~I"
        config_6 = module_0.Config(str_1)
        assert config_6.name == "MI~I"
        config_7 = module_0.Config(str_1)
        assert config_7.name == "MI~I"
        config_8 = module_0.Config()
        assert config_8.name is None
        config_9 = module_0.Config()
        assert config_9.name is None
        config_10 = module_0.Config()
        assert config_10.name is None
        config_11 = module_0.Config()
        assert config_11.name is None
        config_12 = module_0.Config()
        assert config_12.name is None
        config_13 = module_0.Config()
        assert config_13.name is None
        config_14 = module_0.Config()
        assert config_14.name is None
    except BaseException:
        pass
