# coding=utf-8
# Automatically generated by Pynguin.
import pytest

import mridc.collections.segmentation.parts.transforms as module_0


def test_case_0():
    int_0 = -1161
    int_1 = 979
    bool_0 = True
    list_0 = []
    tuple_0 = None
    bool_1 = False
    int_2 = 1888
    j_r_s_m_r_i_data_transforms_0 = module_0.JRSMRIDataTransforms(
        int_0, int_1, bool_0, bool_0, int_0, list_0, tuple_0, bool_1, int_2, bool_1
    )
    assert j_r_s_m_r_i_data_transforms_0.complex_data == -1161
    assert j_r_s_m_r_i_data_transforms_0.coil_combination_method is False
    assert j_r_s_m_r_i_data_transforms_0.dimensionality == 2
    assert j_r_s_m_r_i_data_transforms_0.mask_func is None
    assert j_r_s_m_r_i_data_transforms_0.shift_mask is False
    assert j_r_s_m_r_i_data_transforms_0.mask_center_scale == pytest.approx(
        0.02, abs=0.01, rel=0.01)
    assert j_r_s_m_r_i_data_transforms_0.half_scan_percentage == pytest.approx(
        0.0, abs=0.01, rel=0.01)
    assert j_r_s_m_r_i_data_transforms_0.remask is False
    assert j_r_s_m_r_i_data_transforms_0.crop_size is None
    assert j_r_s_m_r_i_data_transforms_0.kspace_crop is False
    assert j_r_s_m_r_i_data_transforms_0.crop_before_masking is True
    assert j_r_s_m_r_i_data_transforms_0.kspace_zero_filling_size is None
    assert j_r_s_m_r_i_data_transforms_0.normalize_inputs is False
    assert j_r_s_m_r_i_data_transforms_0.max_norm is True
    assert j_r_s_m_r_i_data_transforms_0.fft_centered is True
    assert j_r_s_m_r_i_data_transforms_0.fft_normalization == "ortho"
    assert j_r_s_m_r_i_data_transforms_0.spatial_dims == [-2, -1]
    assert j_r_s_m_r_i_data_transforms_0.coil_dim == -1
    assert j_r_s_m_r_i_data_transforms_0.apply_prewhitening == 979
    assert j_r_s_m_r_i_data_transforms_0.gcc is None
    assert j_r_s_m_r_i_data_transforms_0.use_seed is True
