# coding=utf-8
# Automatically generated by Pynguin.
import mridc.core.conf.hydra_runner as module_0


def test_case_0():
    str_0 = "\n+ENg!X+'w"
    bytes_0 = b"\xaa\x16!]\xc4n"
    callable_0 = module_0.hydra_runner()
    callable_1 = module_0.hydra_runner(str_0, bytes_0)
    callable_2 = module_0.hydra_runner(str_0)
    callable_3 = module_0.hydra_runner(str_0)
    none_type_0 = None
    callable_4 = module_0.hydra_runner(none_type_0)
    callable_5 = module_0.hydra_runner(str_0)
    callable_6 = module_0.hydra_runner()
    list_0 = []
    bool_0 = False
    tuple_0 = bool_0, list_0
    callable_7 = module_0.hydra_runner(str_0, tuple_0)
    callable_8 = module_0.hydra_runner(list_0)
    callable_9 = module_0.hydra_runner()
    callable_10 = module_0.hydra_runner(str_0, str_0)
    var_0 = None
    callable_11 = module_0.hydra_runner(str_0, bytes_0)
    callable_12 = module_0.hydra_runner(var_0)
    callable_13 = module_0.hydra_runner()
    callable_14 = module_0.hydra_runner()
    callable_15 = module_0.hydra_runner()
    callable_16 = module_0.hydra_runner(str_0)
    callable_17 = module_0.hydra_runner(str_0)
    callable_18 = module_0.hydra_runner(str_0, str_0)
    callable_19 = module_0.hydra_runner(str_0)
    callable_20 = module_0.hydra_runner(str_0, str_0)
    callable_21 = module_0.hydra_runner(str_0)
    callable_22 = module_0.hydra_runner(str_0)
    callable_23 = module_0.hydra_runner(str_0, str_0)
    callable_24 = module_0.hydra_runner(str_0)


def test_case_1():
    callable_0 = module_0.hydra_runner()
    callable_1 = module_0.hydra_runner()
    callable_2 = module_0.hydra_runner()
    callable_3 = module_0.hydra_runner()
    int_0 = 33
    var_0 = None
    callable_4 = module_0.hydra_runner(var_0)
    bool_0 = False
    callable_5 = module_0.hydra_runner()
    callable_6 = module_0.hydra_runner(int_0, bool_0)


def test_case_2():
    str_0 = '*)]H#ST(><d"($cHz#K'
    callable_0 = module_0.hydra_runner(str_0, str_0, str_0)
    callable_1 = module_0.hydra_runner(str_0)
    callable_2 = module_0.hydra_runner(str_0)
    bool_0 = False
    str_1 = "_@H-iX2:7g"
    callable_3 = module_0.hydra_runner(str_1)
    callable_4 = module_0.hydra_runner()
    bytes_0 = b"\x10\xdb\xe4\xbd\x8a\x89\x83\x93\xa4\xa0\xd6\rQ"
    callable_5 = module_0.hydra_runner()
    bytes_1 = None
    callable_6 = module_0.hydra_runner(str_0)
    tuple_0 = bool_0, str_1, bytes_0, bytes_1
    callable_7 = module_0.hydra_runner(str_0, tuple_0)
    callable_8 = module_0.hydra_runner(str_0)
    bytes_2 = None
    callable_9 = module_0.hydra_runner(str_0, bytes_2)
    str_2 = "l_4~"
    callable_10 = module_0.hydra_runner()
    str_3 = ""
    var_0 = None
    callable_11 = module_0.hydra_runner(str_3, var_0)
    list_0 = [bool_0, bytes_0, callable_9]
    callable_12 = module_0.hydra_runner(str_1, str_3, list_0)
    callable_13 = module_0.hydra_runner(str_1)
    bytes_3 = b"\xec\x9f\xd9\xa5\x0e"
    callable_14 = module_0.hydra_runner()
    callable_15 = module_0.hydra_runner(str_0)
    callable_16 = module_0.hydra_runner(bytes_3)
    callable_17 = module_0.hydra_runner(str_0)
    float_0 = 2208.0
    callable_18 = module_0.hydra_runner(float_0)
    var_1 = None
    callable_19 = module_0.hydra_runner(str_2, var_1)
    var_2 = None
    callable_20 = module_0.hydra_runner(str_1, var_2)
    callable_21 = module_0.hydra_runner()


def test_case_3():
    callable_0 = module_0.hydra_runner()
    str_0 = " doesn't match hidden"
    float_0 = -1770.1
    callable_1 = module_0.hydra_runner()
    callable_2 = module_0.hydra_runner(str_0)
    callable_3 = module_0.hydra_runner(str_0, str_0)
    callable_4 = module_0.hydra_runner(str_0)
    callable_5 = module_0.hydra_runner(str_0, str_0)
    var_0 = None
    callable_6 = module_0.hydra_runner(var_0)
    callable_7 = module_0.hydra_runner(str_0)
    callable_8 = module_0.hydra_runner(str_0, float_0)
    none_type_0 = None
    callable_9 = module_0.hydra_runner()
    list_0 = None
    float_1 = -3273.5
    callable_10 = module_0.hydra_runner(float_1)
    callable_11 = module_0.hydra_runner(list_0)
    callable_12 = module_0.hydra_runner(none_type_0)
    callable_13 = module_0.hydra_runner(callable_8)
    callable_14 = module_0.hydra_runner()
    callable_15 = module_0.hydra_runner(str_0)
    callable_16 = module_0.hydra_runner(str_0)
    callable_17 = module_0.hydra_runner(str_0, str_0)
    callable_18 = module_0.hydra_runner()
    str_1 = "]W\x0ctwN\x0cgVY"
    callable_19 = module_0.hydra_runner(str_1)
    callable_20 = module_0.hydra_runner()
    callable_21 = module_0.hydra_runner(str_0, callable_1)
    callable_22 = module_0.hydra_runner()
    callable_23 = module_0.hydra_runner()
    callable_24 = module_0.hydra_runner()
    callable_25 = module_0.hydra_runner(str_0)
    callable_26 = module_0.hydra_runner(str_0, str_0)
    callable_27 = module_0.hydra_runner(str_0)
