# coding=utf-8
# Automatically generated by Pynguin.
import mridc.core.optim.novograd as module_0


def test_case_0():
    try:
        str_0 = "BaseMRIDCFormatter"
        float_0 = 284.687
        bytes_0 = b"\x8d\x90\xb6\xe1\x03d\xfc\n\xe7@\xaa\x99\x94\x9d\xfa"
        novograd_0 = module_0.Novograd(str_0, float_0, bytes_0)
    except BaseException:
        pass


def test_case_1():
    try:
        str_0 = None
        dict_0 = {str_0: str_0, str_0: str_0, str_0: str_0}
        bytes_0 = b"\x94.8H"
        tuple_0 = dict_0, str_0, bytes_0
        novograd_0 = module_0.Novograd(tuple_0)
    except BaseException:
        pass


def test_case_2():
    try:
        str_0 = None
        dict_0 = {str_0: str_0, str_0: str_0, str_0: str_0}
        bytes_0 = b"\x94.8H"
        tuple_0 = dict_0, str_0, bytes_0
        novograd_0 = module_0.Novograd(tuple_0)
    except BaseException:
        pass


def test_case_3():
    try:
        str_0 = ".}<K%dBtjf!CNz"
        bool_0 = None
        int_0 = -89
        str_1 = None
        dict_0 = None
        list_0 = []
        bool_1 = True
        tuple_0 = dict_0, str_0, list_0, bool_1
        novograd_0 = module_0.Novograd(bool_0, int_0, str_1, tuple_0)
    except BaseException:
        pass


def test_case_4():
    try:
        bool_0 = False
        set_0 = set()
        bool_1 = True
        bytes_0 = b"\x8e\xa4\xd3\xc29\x00>>\x87\xa7"
        dict_0 = {bool_1: bool_0, bool_1: bool_0, bool_0: bool_0, bytes_0: bool_1}
        novograd_0 = module_0.Novograd(set_0, bool_1, dict_0)
    except BaseException:
        pass


def test_case_5():
    try:
        float_0 = 997.75
        int_0 = -1882
        bytes_0 = b"!\xed\xe4"
        int_1 = 138
        list_0 = [bytes_0, int_0, bytes_0, int_1]
        bytes_1 = b"6h\xe4jZ^\xed\x85\x08X8\xee$"
        bool_0 = True
        float_1 = -239.0
        novograd_0 = module_0.Novograd(bytes_1, bool_0, bytes_0, float_1, list_0, float_0, list_0)
    except BaseException:
        pass
