# coding=utf-8
# Automatically generated by Pynguin.
import mridc.core.neural_types.neural_type as module_0
import mridc.core.utils.neural_type_utils as module_1


def test_case_0():
    str_0 = "s4dCQ0\r"
    neural_type_0 = module_0.NeuralType()
    var_0 = module_1.extract_dynamic_axes(str_0, neural_type_0)
    assert neural_type_0.axes is None
    assert neural_type_0.optional is False
    assert var_0 == {}
