# coding=utf-8
# Automatically generated by Pynguin.
import mridc.collections.common.parts.rnn_utils as module_0


def test_case_0():
    try:
        str_0 = 'o"/(8i\n%dr@{*j~+['
        list_0 = [str_0, str_0]
        var_0 = module_0.rnn_weights_init(list_0)
        assert var_0 is None
    except BaseException:
        pass
