# coding=utf-8
# Automatically generated by Pynguin.
import mridc.utils.metaclasses as module_0


def test_case_0():
    try:
        singleton_0 = module_0.Singleton()
    except BaseException:
        pass


def test_case_1():
    try:
        singleton_0 = module_0.Singleton()
    except BaseException:
        pass


def test_case_2():
    try:
        dict_0 = {}
        list_0 = [dict_0, dict_0, dict_0, dict_0]
        singleton_0 = module_0.Singleton(*list_0)
    except BaseException:
        pass


def test_case_3():
    try:
        singleton_0 = module_0.Singleton()
    except BaseException:
        pass
