# coding=utf-8
# Automatically generated by Pynguin.
import mridc.utils.app_state as module_0


def test_case_0():
    str_0 = "M'g1^R^h"
    app_state_0 = module_0.AppState()
    assert app_state_0.model_parallel_rank is None
    var_0 = app_state_0.register_model_guid(str_0)
    assert var_0 is None
