pretrained: false
checkpoint: None
mode: train

model:
  model_name: VSNET
  num_cascades: 10
  imspace_model_architecture: CONV
  imspace_conv_hidden_channels: 64
  imspace_conv_n_convs: 4
  imspace_conv_batchnorm: false
  coil_combination_method: SENSE
  use_sens_net: false
  sens_chans: 8
  sens_pools: 4
  sens_mask_type: 2D
  train_loss_fn: l1
  val_loss_fn: l1
  fft_centered: True
  fft_normalization: ortho
  spatial_dims:
    - -2
    - -1
  coil_dim: 1

  train_ds:
    data_path: ???
    challenge: multicoil
    coil_combination_method: SENSE
    fft_centered: True
    fft_normalization: ortho
    spatial_dims:
      - -2
      - -1
    coil_dim: 1
    mask_args:
      type: gaussian2d
      accelerations:
        - 10
      center_fractions:
        - 0.7
      scale: 0.02
      shift_mask: false
      use_seed: true
    normalize_inputs: true
    crop_size: None
    crop_before_masking: true
    kspace_zero_filling_size: None
    sample_rate: 1
    batch_size: 1
    shuffle: true
    num_workers: 8
    drop_last: false
    pin_memory: false

  validation_ds:
    data_path: ???
    challenge: multicoil
    coil_combination_method: SENSE
    fft_centered: True
    fft_normalization: ortho
    spatial_dims:
      - -2
      - -1
    coil_dim: 1
    mask_args:
      type: gaussian2d
      accelerations:
        - 10
      center_fractions:
        - 0.7
      scale: 0.02
      shift_mask: false
      use_seed: false
    normalize_inputs: true
    crop_size: None
    crop_before_masking: true
    kspace_zero_filling_size: None
    sample_rate: 1
    batch_size: 1
    shuffle: false
    num_workers: 8
    drop_last: false
    pin_memory: false

  optim:
    name: adam
    lr: 0.001
    betas:
      - 0.9
      - 0.98
    weight_decay: 0.0
    sched:
      name: InverseSquareRootAnnealing
      min_lr: 0.0
      last_epoch: -1
      warmup_ratio: 0.1

trainer:
  strategy: ddp
  gpus: 1
  num_nodes: 1
  max_epochs: 20
  precision: 16
  enable_checkpointing: false
  logger: false
  log_every_n_steps: 50
  check_val_every_n_epoch: -1
  max_steps: -1

exp_manager:
  name: ???
  create_tensorboard_logger: true
  files_to_copy: [ ]
