pretrained: false
checkpoint: ???
mode: test

model:
  model_name: ZF
  coil_combination_method: SENSE
  fft_centered: True
  fft_normalization: ortho
  spatial_dims:
    - -2
    - -1
  coil_dim: 1

  test_ds:
    data_path: ???
    challenge: multicoil
    coil_combination_method: SENSE
    fft_centered: True
    fft_normalization: ortho
    spatial_dims:
      - -2
      - -1
    coil_dim: 1
    mask_args:
      type: gaussian2d
      accelerations:
      - 10
      center_fractions:
      - 0.7
      scale: 0.02
      shift_mask: false
      use_seed: false
    normalize_inputs: true
    crop_size: None
    crop_before_masking: true
    kspace_zero_filling_size: None
    sample_rate: 1
    batch_size: 1
    shuffle: false
    num_workers: 8
    drop_last: false
    pin_memory: false

trainer:
  strategy: ddp
  gpus: 1
  num_nodes: 1
  max_epochs: 200
  precision: 16
  enable_checkpointing: false
  logger: false
  log_every_n_steps: 50
  check_val_every_n_epoch: -1
  max_steps: -1

exp_manager:
  name: ???
  create_tensorboard_logger: true
  files_to_copy: [ ]
