pretrained: false
checkpoint: None
mode: train

model:
  model_name: LPDNET
  num_primal: 5
  num_dual: 5
  num_iter: 5
  primal_model_architecture: UNET
  primal_in_channels: 2
  primal_out_channels: 2
  primal_unet_num_filters: 16
  primal_unet_num_pool_layers: 2
  primal_unet_dropout_probability: 0.0
  primal_unet_padding_size: 11
  primal_unet_normalize: true
  dual_model_architecture: UNET
  dual_in_channels: 2
  dual_out_channels: 2
  dual_unet_num_filters: 16
  dual_unet_num_pool_layers: 2
  dual_unet_dropout_probability: 0.0
  dual_unet_padding_size: 11
  dual_unet_normalize: true
  dimensionality: 2
  train_loss_fn: l1
  val_loss_fn: l1
  coil_combination_method: SENSE
  fft_centered: false
  fft_normalization: backward
  spatial_dims:
    - -2
    - -1
  coil_dim: 1
  use_sens_net: false
  consecutive_slices: 1
  log_images: true

  train_ds:
    data_path: ???
    coil_sensitivity_maps_path: None
    mask_path: None
    sample_rate: 1
    volume_sample_rate: None
    use_dataset_cache: false
    dataset_cache_file: None
    num_cols: None
    consecutive_slices: 1
    data_saved_per_slice: false
    apply_prewhitening: false
    apply_gcc: false
    coil_combination_method: SENSE
    dimensionality: 2
    mask_args:
      type: poisson2d
      accelerations:
        - 10
      center_fractions:
        - 0.7
      scale: 0.02
      shift_mask: false
      use_seed: true
    half_scan_percentage: 0.0
    remask: false
    crop_size: None
    kspace_crop: false
    crop_before_masking: true
    kspace_zero_filling_size: None
    normalize_inputs: true
    normalization_type: max
    fft_centered: false
    fft_normalization: backward
    spatial_dims:
      - -2
      - -1
    coil_dim: 1
    use_seed: true
    batch_size: 1
    shuffle: true
    num_workers: 8
    pin_memory: false
    drop_last: false

  validation_ds:
    data_path: ???
    coil_sensitivity_maps_path: None
    mask_path: None
    sample_rate: 1
    volume_sample_rate: None
    use_dataset_cache: false
    dataset_cache_file: None
    num_cols: None
    consecutive_slices: 1
    data_saved_per_slice: false
    apply_prewhitening: false
    apply_gcc: false
    coil_combination_method: SENSE
    dimensionality: 2
    mask_args:
      type: poisson2d
      accelerations:
        - 10
      center_fractions:
        - 0.7
      scale: 0.02
      shift_mask: false
      use_seed: false
    half_scan_percentage: 0.0
    remask: false
    crop_size: None
    kspace_crop: false
    crop_before_masking: true
    kspace_zero_filling_size: None
    normalize_inputs: true
    normalization_type: max
    fft_centered: false
    fft_normalization: backward
    spatial_dims:
      - -2
      - -1
    coil_dim: 1
    use_seed: false
    batch_size: 1
    shuffle: true
    num_workers: 8
    pin_memory: false
    drop_last: false

  optim:
    name: adam
    lr: 0.001
    betas:
      - 0.9
      - 0.98
    weight_decay: 0.0
    sched:
      name: InverseSquareRootAnnealing
      min_lr: 0.0
      last_epoch: -1
      warmup_ratio: 0.1

trainer:
  strategy: ddp
  accelerator: gpu
  devices: 1
  num_nodes: 1
  max_epochs: 200
  precision: 16
  enable_checkpointing: false
  logger: false
  log_every_n_steps: 50
  check_val_every_n_epoch: -1
  max_steps: -1

exp_manager:
  exp_dir: ???
  create_tensorboard_logger: true
  create_wandb_logger: false
  wandb_logger_kwargs:
    project: ???
  files_to_copy: [ ]
