pretrained: false
checkpoint: None
mode: train

model:
  model_name: XPDNET
  num_primal: 5
  num_dual: 1
  num_iter: 20
  use_primal_only: true
  kspace_model_architecture: CONV
  dual_conv_hidden_channels: 16
  dual_conv_num_dubs: 2
  dual_conv_batchnorm: false
  image_model_architecture: MWCNN
  mwcnn_hidden_channels: 16
  mwcnn_num_scales: 2
  mwcnn_bias: true
  mwcnn_batchnorm: false
  normalize_image: false
  coil_combination_method: SENSE
  use_sens_net: false
  sens_chans: 8
  sens_pools: 4
  sens_mask_type: 2D
  train_loss_fn: l1
  eval_loss_fn: l1
  fft_centered: True
  fft_normalization: ortho
  spatial_dims:
    - -2
    - -1

  train_ds:
    data_path: ???
    dataset_type: FastMRI
    challenge: multicoil
    coil_combination_method: SENSE
    fft_centered: True
    fft_normalization: ortho
    spatial_dims:
      - -2
      - -1
    mask_args:
      type: gaussian2d
      accelerations:
      - 10
      center_fractions:
      - 0.7
      scale: 0.02
      shift_mask: false
      use_seed: true
    normalize_inputs: true
    crop_size: None
    crop_before_masking: true
    kspace_zero_filling_size: None
    sample_rate: 1
    batch_size: 1
    shuffle: true
    num_workers: 8
    drop_last: false
    pin_memory: false

  validation_ds:
    data_path: ???
    dataset_type: FastMRI
    challenge: multicoil
    coil_combination_method: SENSE
    fft_centered: True
    fft_normalization: ortho
    spatial_dims:
      - -2
      - -1
    mask_args:
      type: gaussian2d
      accelerations:
      - 10
      center_fractions:
      - 0.7
      scale: 0.02
      shift_mask: false
      use_seed: false
    normalize_inputs: true
    crop_size: None
    crop_before_masking: true
    kspace_zero_filling_size: None
    sample_rate: 1
    batch_size: 1
    shuffle: false
    num_workers: 8
    drop_last: false
    pin_memory: false

  optim:
    name: adam
    lr: 0.0001
    betas:
      - 0.9
      - 0.98
    weight_decay: 0.0
    sched:
      name: InverseSquareRootAnnealing
      min_lr: 0.0
      last_epoch: -1
      warmup_ratio: 0.1

trainer:
  strategy: ddp
  gpus: 1
  num_nodes: 1
  max_epochs: 20
  precision: 16
  enable_checkpointing: false
  logger: false
  log_every_n_steps: 50
  check_val_every_n_epoch: -1
  max_steps: -1

exp_manager:
  name: ???
  create_tensorboard_logger: true
  files_to_copy: [ ]
